name: Waka Readme

on:
  schedule:
    # Runs every 2 hours
    - cron: '0 */4 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          LOCALE: "fr"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_SHORT_INFO: "False"
          SHOW_LINES_OF_CODE: "False"
          SHOW_OS: "True"
          COMMIT_BY_ME: "True"
          COMMIT_MESSAGE: "XY: dev Stats updated"
          SHOW_LOC_CHART: "False"
          
