name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 00:00AM UTC
    - cron: '0 0 * * *'

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - name: Debug Start
        run: echo "Debugging started..."

      - uses: actions/checkout@v2 # Check out your repository

      - name: Debug Environment Variables
        run: |
          echo "WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}"
          echo "GH_TOKEN: ${{ secrets.GH_TOKEN }}"

      - name: Debug Action Inputs
        run: |
          echo "SHOW_PROJECTS: False"
          echo "SHOW_LINES_OF_CODE: True"
          echo "SHOW_LOC_CHART: False"
          echo "LOCALE: en"

      - uses: anmol098/waka-readme-stats@master #PLEASE USE MASTER BRANCH
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROJECTS: "False"
          SHOW_LINES_OF_CODE: "True"
          SHOW_LOC_CHART: "False"
          LOCALE: "en"

      - name: Debug End
        run: echo "Debugging completed."
